DROP DATABASE IF EXISTS etracker_DB;
CREATE DATABASE etracker_DB;
USE etracker_DB;
DROP TABLE IF EXISTS Department;
DROP TABLE IF EXISTS Role;
DROP TABLE IF EXISTS Employee;

CREATE TABLE Department
(
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    CONSTRAINT UC_name UNIQUE(name)
);

CREATE TABLE Role 
(
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(30) NOT NULL,
    salary DECIMAL(10,2) default 0,
    department_id INT UNSIGNED,
    CONSTRAINT FK_department FOREIGN KEY (department_id) REFERENCES Department(id) ON DELETE CASCADE
);

CREATE TABLE Employee
(
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(30) NOT NULL,
    last_name VARCHAR(30) NOT NULL,
    role_id INT UNSIGNED,
    CONSTRAINT fk_role FOREIGN KEY (role_id) REFERENCES Role(id) ON DELETE CASCADE,
    manager_id INT UNSIGNED,
    CONSTRAINT FK_manager FOREIGN KEY (manager_id) REFERENCES Employee(id) ON DELETE SET NULL
);